server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security=DEBUG:

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petlendar
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret:
    key: petlendar_password_key_by_seob_1234567890
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

