server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petlendar
    username: postgres
    password: 1234
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

firebase:
  secret:
    key:
      path: /app/firebase/firebase_service_key.json