server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petlendar
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
