server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/petlendar
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs # Gateway 에서 접근할 수 있도록 통일된 경로 설정
  enable-spring-security: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
