spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/petlendar
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect